name: MLOps (DVC + MLflow + Pages)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  repro-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: pip install -r requirements.txt

      # DVC akan otomatis mendownload iris.csv via import-url ketika dibutuhkan
      - name: Run DVC pipeline
        run: dvc repro

      - name: Upload MLflow runs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: mlruns/

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: reports/public

  deploy-pages:
    needs: repro-pipeline
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: html-report
          path: public

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4